"""Add owner_id to the Rating Model, or foreign key

Revision ID: 08595b32f688
Revises: 20e350566fc0
Create Date: 2022-01-17 23:42:46.426804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08595b32f688'
down_revision = '20e350566fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'ratings', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ratings', 'owner_id')
    op.drop_column('ratings', 'recipe_id')
    # ### end Alembic commands ###
