"""Change Rating model to only have recipe id, likes and dislikes

Revision ID: 12d8154ca7a1
Revises: 
Create Date: 2022-01-18 15:53:20.064037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d8154ca7a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'ratings', 'users', ['owner_id'], ['id'])
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
