"""empty message

Revision ID: 20e350566fc0
Revises: 54c7b851adad
Create Date: 2022-01-17 23:39:02.555302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e350566fc0'
down_revision = '54c7b851adad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ratings', 'recipe_id')
    # ### end Alembic commands ###
