"""Fix owner in Rating to rating_owner

Revision ID: 54c7b851adad
Revises: dd7855171a04
Create Date: 2022-01-17 23:33:55.392710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c7b851adad'
down_revision = 'dd7855171a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ratings', 'recipe_id')
    # ### end Alembic commands ###
